/* eslint-disable react/jsx-props-no-spreading */
/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Logotyp (https://sketchfab.com/Logotyp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nokia-3310-bcce376c3c324fc59a20bcdd0b715417
title: Nokia 3310
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {
    initialShadingGroup: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']): JSX.Element {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('gltf/nokia_3310/scene.gltf') as GLTFResult;
  return (
    <group ref={group} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.0, 0]} rotation={[0, 0, 0]}>
          <mesh
            castShadow
            material={materials.initialShadingGroup}
            geometry={nodes.mesh_0.geometry}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
